A_Blog/urls.py
from django.urls import path, include
from . import views

app_name= "Blog"

urlpatterns = [
    path('', views.index, name="index"),

    ]

Ariadne/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('A_Blog.urls', namespace="A_Blog_App")),
    path('', include('Ariadne_App.urls')),
]

Ariadne_App/urls.py
from django.urls import path, include
from . import views


urlpatterns = [
    path('', views.index, name="index"),
    path("add", views.addTodo, name="add"),
    path("complete/<todo_id>", views.completeTodo, name="complete"),
    path("deletecomplete", views.deleteCompleted, name="deletecomplete"),
    path("deleteall", views.deleteAll, name="deleteall"),
    path("deleteselected/<todo_id>", views.deleteSelected, name="deleteselected"),
    path('blog/', include('A_Blog.urls'), name="Blog"),
    ]

A_Blog/models.py
from django.db import models

# Create your models here.
class memo(models.Model):
    title = models.CharField(max_length=60)
    message = models.CharField(max_length=2000)
    timestamp = models.DateTimeField(auto_now_add=True, blank=True)

    def __str__(self):
        return self.text

Ariadne_App/models.py
from django.db import models

# Create your models here.
class Todo(models.Model):
    text = models.CharField(max_length=60)
    complete = models.BooleanField(default=False)

    def __str__(self):
        return self.text

Ariadne_App/forms.py
from django import forms

class TodoForm(forms.Form):
    text = forms.CharField(max_length=60, widget=forms.TextInput(
    attrs={"class":"form-control", "placeholder": "Enter todo i.e. delete junk files", "aria-label":"Todo", "aria-describedby": "add-btn"}
    ))

A_Blog/views.py
from django.shortcuts import render, redirect
from django.views.decorators.http import require_POST
from django.http import HttpResponse

# Create your views here.
def index(request):
    return render(request, "A_Blog_App/index.html")

def build_post(request, blog_id):
    

Ariadne_App/views.py
from django.shortcuts import render, redirect
from .models import Todo
from .forms import TodoForm
from django.views.decorators.http import require_POST
# Create your views here.
def index(request):
    todo_list = Todo.objects.order_by("id")
    form = TodoForm()
    context = {'todo_list' : todo_list, "form": form}
    return render(request, "Ariadne_App/index.html", context)

@require_POST
def addTodo(request):
    form = TodoForm(request.POST)

    print(request.POST["text"])

    if form.is_valid():
        new_todo = Todo(text=request.POST["text"])
        new_todo.save()

    return redirect('index')

def completeTodo(request, todo_id):
    todo = Todo.objects.get(pk=todo_id)
    todo.complete = True
    todo.save()

    return redirect("index")

def deleteCompleted(request):
    Todo.objects.filter(complete__exact=True).delete()

    return redirect("index")

def deleteAll(request):
    Todo.objects.all().delete()

    return redirect("index")

def deleteSelected(request, todo_id):
    todo = Todo.objects.get(pk=todo_id)
    todo.delete()

    return redirect("index")

A_Blog/templates/A_Blog_App/index.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="=utf-8">
    <!-- <script src="{% static 'A_Blog_App\js\jquery.js' %}"></script>
    <script src="{% static 'A_Blog_App\js\clock.js' %}"></script> -->

    <link rel="stylesheet" href="{% static 'A_Blog_App/css/css/font-awesome.css' %}">
    <link rel="stylesheet" href="{% static 'A_Blog_App/css/cyborg-bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'A_Blog_App/styles.css' %}"> <!-- line not tested to work -->

  </head>

    <header id="boilerplate">
      <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarColor01">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Meow</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Something else</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">About</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" placeholder="Search" type="text">
      <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>
    </header>
  <body>
    <div id="page" class="container">
      <div id="block1" class="row">
        <div id="#" class="col-md-8">
          <h2>test</h2>
      </div>
    </div>
  </div>
    <footer id="footer-plate">
      <p>footer placeholder</p>
    </footer>
  </body>
</html>


<script src="Clock.js"></script>

Ariadne_App/templates/Ariadne_App/index.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="=utf-8">
    <script src="{% static 'Ariadne_App\js\jquery.js' %}"></script>
    <script src="{% static 'Ariadne_App\js\clock.js' %}"></script>

    <link rel="stylesheet" href="{% static 'Ariadne_App/css/css/font-awesome.css' %}">
    <link rel="stylesheet" href="{% static 'Ariadne_App/css/cyborg-bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'Ariadne_App/styles.css' %}"> <!-- line not tested to work -->

  </head>

    <header id="boilerplate">
      <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarColor01">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'A_Blog_App:index' %}">Meow</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Something else</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">About</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" placeholder="Search" type="text">
      <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>
    </header>
  <body>
    <div id="page" class="container">

      <div id="block1" class="row">
        <div id="todo" class="col-md-8">
          <h2>WHAT DO YOU WANT TO DO TODAY?</h2>
          <!-- here is where the form is (aka the text field where user input goes)  -->
          <form action="{% url 'add' %}" method="POST" role="form">
            {% csrf_token %}

						<div class="form-group">
							<div class="input-group">
                {{ form.text }}
							  <span class="input-group-btn">
								  <button type="submit" class="btn btn-outline-success" id="add-btn">ADD</button>
							  </span>
							</div>
						</div>
					</form>
          <!-- here is where the items are added to the list -->
          <ul class="list-group t20">
            {% for todo in todo_list %}
              {% if todo.complete %}
              <li class="list-group-item todo-completed">{{ todo.text }}
                <!--directly below is the icon for the completed stuff  -->
                <a href="{% url 'deleteselected' todo.id %}"><i id="del-icon" class="fa fa-remove"></i> </a></li>
              {% else %}
              <a href="{% url 'complete' todo.id %}"><li class="list-group-item">{{ todo.text }}
                <!-- directly below is the icon for the not completed stuff  -->
                <a href="{% url 'deleteselected' todo.id %}"><i id="del-icon" class="fa fa-remove"></i></a></li></a>
              {% endif %}
            {% endfor %}

					</ul>
          <!-- here is the delete buttons -->
          <div class="row t10">
            <div class="col-lg-12">
              <div class="btn-toolbar">
                <div class="del-btn-group">
                  <a href="{% url 'deletecomplete' %} "<button type="button" class="btn btn-outline-info">
                    <i class="glyphicon glyphicon-trash"></i> DELETE COMPLETED
                  </button></a>
                </div>
                <div class="del-btn-group">
                  <a href="{% url 'deleteall' %}"<button type="button" class="btn btn-outline-info">
                    <i class="glyphicon glyphicon-trash"></i> DELETE ALL
                  </button> </a>
                </div>
              </div>
            </div>
          </div>
          <!-- Display list of user input todo items from db here -->
      </div>
      <div id="clock timer" class="col-md-4 jumbotron">
          <div class="alert alert-dismissible alert-info">
            <div id="clock"> Time </div>
              <span id="hours"></span>
              <span id="minutes"></span>
              <span id="seconds"></span>
            </div>
          </div>
<!-- Start of note taking area  -->
          <div id="text_box">
            <h2>enter your thoughts into the box...</h2>
            <textarea rows="4" cols="90"></textarea>
          </div>
    </div>
  </div>
    <footer id="footer-plate">
      <p>footer placeholder</p>
    </footer>
  </body>
</html>


<script src="Clock.js"></script>